version: '3.3'

# Services
services:

  # Nginx
  nginx:
    image: nginx:1.21-alpine
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./src:/var/www/php
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - ./logs/nginx-access.log:/var/log/nginx/access.log

      - phpmyadmindata:/var/www/phpmyadmin
    depends_on:
      - php
      - phpmyadmin

  # PHP FPM
  php:
    build:
      context: .
      dockerfile: php-dockerfile
    ports:
      - 9000:9000
    working_dir: /var/www/php
    volumes:
      - ./src:/var/www/php
    depends_on:
      - mariadb

  # Mariadb
  mariadb:
    image: mariadb:10.7
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mariadbdata:/var/lib/mysql

  # Phpmyadmin FPM
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1-fpm-alpine
    volumes:
      - phpmyadmindata:/var/www/html
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mariadb

# Volumes
volumes:
  mariadbdata:
  phpmyadmindata:

